package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"mem/adapters/primary/setup"
	"mem/domain"
)

// uninstallAgentFiles son los mismos archivos que CmdInstall puede haber
// modificado con el bloque de protocolo de memoria.
var uninstallAgentFiles = []string{"AGENTS.md", "CLAUDE.md", "CLAUDE.txt", ".cursorrules", ".windsurfrules"}

// uninstallMCPConfig es un archivo de configuración MCP por proyecto junto con
// la clave bajo la que ese agente registra sus servidores.
type uninstallMCPConfig struct {
	path string
	key  string
}

// uninstallMCPConfigs se DERIVA de la matriz de canales (feature 022), que es
// la declaración única de qué artefacto corresponde a cada agente, canal y
// ámbito.
//
// Antes era una lista escrita a mano, y ahí estaba el defecto: la instalación
// escribía la configuración de un agente con un esquema propio y esta lista
// solo conocía el de los demás, así que esa entrada sobrevivía a toda
// desinstalación. Derivarla elimina la posibilidad de que vuelvan a separarse.
//
// ~/.codex/config.toml queda fuera por ámbito, no por olvido: es de la persona
// y lo comparten todos sus proyectos. La matriz lo refleja y se informa en vez
// de tocarlo.
var uninstallMCPConfigs = buildUninstallMCPConfigs()

func buildUninstallMCPConfigs() []uninstallMCPConfig {
	vistos := map[string]bool{}
	var out []uninstallMCPConfig
	for _, c := range domain.CellsForActivity(domain.ActivityUninstall) {
		if c.Kind != domain.KindServerConfig || c.ConfigKey == "" {
			continue
		}
		ruta := filepath.Join(c.Path...)
		clave := ruta + "|" + c.ConfigKey
		if vistos[clave] {
			continue
		}
		vistos[clave] = true
		out = append(out, uninstallMCPConfig{path: ruta, key: c.ConfigKey})
	}
	// Los agentes sin canales propios más allá del registro del servidor no
	// tienen fila en la matriz todavía; se conservan aquí hasta que la tengan.
	for _, extra := range []uninstallMCPConfig{
		{filepath.Join(".cursor", "mcp.json"), "mcpServers"},
		{filepath.Join(".windsurf", "mcp_config.json"), "mcpServers"},
		{filepath.Join(".cline", "mcp_settings.json"), "mcpServers"},
	} {
		out = append(out, extra)
	}
	return out
}

// CmdUninstall acepta --yes en cualquier posición (antes o después del
// directorio) — flag.FlagSet de stdlib deja de parsear flags en el primer
// argumento posicional, lo cual no sirve para `mem uninstall [dir] [--yes]`.
func CmdUninstall(deps *Deps, args []string) {
	yes := false
	var rest []string
	for _, a := range args {
		if a == "--yes" {
			yes = true
			continue
		}
		rest = append(rest, a)
	}

	target := "."
	if len(rest) > 0 {
		target = rest[0]
	}

	target, err := filepath.Abs(target)
	if err != nil {
		fail("ruta inválida: %v", err)
	}
	stat, err := os.Stat(target)
	if err != nil {
		fail("no existe: %v", err)
	}
	if !stat.IsDir() {
		fail("%s no es un directorio", target)
	}

	if !yes {
		prompt := fmt.Sprintf(
			"Esto eliminará el binario, hooks, configuración MCP, entradas en AGENTS.md/CLAUDE.md y TODA la memoria guardada en %s. ¿Continuar?",
			target,
		)
		if !ConfirmAction(os.Stdin, prompt) {
			fmt.Println("Desinstalación cancelada. No se eliminó nada.")
			return
		}
	}

	fmt.Printf("🗑️  Desinstalando gomemory de %s\n\n", target)

	removeIntegrationBlocks(target)
	removeMCPEntries(target)
	removeClaudePlugin(target)
	removeClaudePermissions(target)
	removeOpenCodeArtifacts(target)
	removeNativeWrappers(target)
	removeMemoryDir(target, deps.ProjectRepo.MemDir())
	removeBinary(target)

	fmt.Println()
	fmt.Println("✅ Desinstalación completa.")
}

func removeIntegrationBlocks(target string) {
	for _, fname := range uninstallAgentFiles {
		fpath := filepath.Join(target, fname)
		data, err := os.ReadFile(fpath)
		if err != nil {
			fmt.Printf("  ℹ️  %s: no encontrado\n", fname)
			continue
		}
		content := string(data)

		loc := versionMarkerPattern.FindStringIndex(content)
		if loc == nil {
			fmt.Printf("  ℹ️  %s: sin bloque de protocolo de memoria reconocible, se conserva tal cual\n", fname)
			continue
		}
		idx := loc[0]

		trimmed := strings.TrimRight(content[:idx], "\n")
		if trimmed == "" || isAutoGeneratedTitle(trimmed) {
			if err := os.Remove(fpath); err != nil {
				fmt.Printf("  ⚠️  %s: error al eliminar archivo vacío tras quitar el bloque: %v\n", fname, err)
				continue
			}
			fmt.Printf("  ✅ %s: eliminado (era generado enteramente por mem install)\n", fname)
			continue
		}

		if err := os.WriteFile(fpath, []byte(trimmed+"\n"), 0644); err != nil {
			fmt.Printf("  ⚠️  %s: error al quitar el bloque: %v\n", fname, err)
			continue
		}
		fmt.Printf("  ✅ %s: bloque de protocolo de memoria removido\n", fname)
	}
}

// isAutoGeneratedTitle detecta si lo que queda tras quitar el bloque de
// protocolo es exactamente el título que las versiones anteriores de
// `mem install` generaban para archivos creados desde cero (sin contenido
// previo del usuario) — en ese caso el archivo entero era generado y debe
// eliminarse, no solo el bloque.
//
// La feature 021 retiró esa generación, pero los títulos siguen listados aquí:
// `mem uninstall` debe poder limpiar proyectos instalados con versiones
// anteriores, que son justamente los que tienen esos archivos.
func isAutoGeneratedTitle(trimmed string) bool {
	switch trimmed {
	case "# Instrucciones para agentes AI", "# Instrucciones para Claude Code":
		return true
	default:
		return false
	}
}

func removeMCPEntries(target string) {
	for _, conf := range uninstallMCPConfigs {
		rel := conf.path
		fpath := filepath.Join(target, rel)
		data, err := os.ReadFile(fpath)
		if err != nil {
			fmt.Printf("  ℹ️  %s: no encontrado\n", rel)
			continue
		}

		var cfg map[string]interface{}
		if err := json.Unmarshal(data, &cfg); err != nil {
			fmt.Printf("  ⚠️  %s: JSON inválido, se conserva sin tocar\n", rel)
			continue
		}

		ms, ok := cfg[conf.key].(map[string]interface{})
		if !ok {
			fmt.Printf("  ℹ️  %s: sin entrada gomemory\n", rel)
			continue
		}
		if _, has := ms["gomemory"]; !has {
			fmt.Printf("  ℹ️  %s: sin entrada gomemory\n", rel)
			continue
		}

		delete(ms, "gomemory")
		cfg[conf.key] = ms

		out, _ := json.MarshalIndent(cfg, "", "  ")
		if err := os.WriteFile(fpath, out, 0644); err != nil {
			fmt.Printf("  ⚠️  %s: error al escribir: %v\n", rel, err)
			continue
		}
		fmt.Printf("  ✅ %s: entrada gomemory removida\n", rel)
	}

	fmt.Println("  ℹ️  ~/.codex/config.toml no se modifica automáticamente — es un archivo global compartido entre proyectos; si instalaste el agente codex, remueve manualmente la tabla [mcp_servers.\"gomemory_*\"] correspondiente.")
}

func removeClaudePlugin(target string) {
	pluginDir := filepath.Join(target, ".claude", "plugins", "gomemory")
	if _, err := os.Stat(pluginDir); err == nil {
		if err := os.RemoveAll(pluginDir); err != nil {
			fmt.Printf("  ⚠️  %s: error al eliminar: %v\n", pluginDir, err)
		} else {
			fmt.Printf("  ✅ %s: eliminado\n", pluginDir)
		}
	} else {
		fmt.Println("  ℹ️  .claude/plugins/gomemory: no encontrado")
	}

	settingsPath := filepath.Join(target, ".claude", "settings.json")
	data, err := os.ReadFile(settingsPath)
	if err != nil {
		fmt.Println("  ℹ️  .claude/settings.json: no encontrado")
		return
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		fmt.Println("  ⚠️  .claude/settings.json: JSON inválido, se conserva sin tocar")
		return
	}

	hooks, ok := settings["hooks"].(map[string]interface{})
	if !ok {
		fmt.Println("  ℹ️  .claude/settings.json: sin hooks de gomemory")
		return
	}

	changed := false
	for _, key := range []string{"SessionStart", "PreCompact", "UserPromptSubmit", "SessionEnd", "Stop", "SubagentStart", "SubagentStop", "PostToolUse"} {
		entries, ok := hooks[key].([]interface{})
		if !ok {
			continue
		}
		kept := make([]interface{}, 0, len(entries))
		for _, e := range entries {
			// Reconoce tanto el formato objeto nuevo (command "mem hook ...")
			// como el legado ([]string a scripts/*.sh del plugin).
			if setup.IsGomemoryHookEntry(e) {
				changed = true
				continue
			}
			kept = append(kept, e)
		}
		if len(kept) == 0 {
			delete(hooks, key)
		} else {
			hooks[key] = kept
		}
	}

	if !changed {
		fmt.Println("  ℹ️  .claude/settings.json: sin hooks de gomemory")
		return
	}

	settings["hooks"] = hooks
	out, _ := json.MarshalIndent(settings, "", "  ")
	if err := os.WriteFile(settingsPath, out, 0644); err != nil {
		fmt.Printf("  ⚠️  .claude/settings.json: error al escribir: %v\n", err)
		return
	}
	fmt.Println("  ✅ .claude/settings.json: hooks de gomemory removidos")
}

func removeClaudePermissions(target string) {
	changed, err := setup.RemoveClaudePermissions(target)
	if err != nil {
		fmt.Printf("  ⚠️  .claude/settings.json: error al limpiar permisos: %v\n", err)
		return
	}
	if !changed {
		fmt.Println("  ℹ️  .claude/settings.json: sin permisos de gomemory")
		return
	}
	fmt.Println("  ✅ .claude/settings.json: permisos de gomemory removidos")
}

// removeOpenCodeArtifacts retira lo que InstallOpenCode escribe y que la entrada
// MCP no cubre: los permisos pre-aprobados del opencode.json y el plugin de
// usuario.
//
// Existe por simetría con removeClaudePlugin y removeClaudePermissions: la
// desinstalación retiraba por completo los artefactos de un agente y dejaba
// intactos los del otro. El registro de capacidades no detecta esta clase de
// asimetría, porque describe la activación y no la retirada.
func removeOpenCodeArtifacts(target string) {
	changed, err := setup.RemoveOpenCodePermissions(target)
	switch {
	case err != nil:
		fmt.Printf("  ⚠️  opencode.json: error al limpiar permisos: %v\n", err)
	case changed:
		fmt.Println("  ✅ opencode.json: permisos de gomemory removidos")
	default:
		fmt.Println("  ℹ️  opencode.json: sin permisos de gomemory")
	}

	// El plugin de OpenCode NO se elimina: vive en el HOME y lo comparten todos
	// los proyectos. Se informa su ruta, misma política que ~/.codex/config.toml.
	if ruta := setup.OpenCodePluginPath(); ruta != "" {
		fmt.Printf("  ℹ️  %s no se elimina — es de ámbito de usuario y lo comparten todos tus proyectos; bórralo a mano si ya no usas gomemory en ninguno.\n", ruta)
	}
}

// removeNativeWrappers retira los envoltorios nativos que la instalación
// genera para cada agente.
//
// Retira archivos, nunca directorios: `.claude/skills` y `.opencode/commands`
// alojan también habilidades de otras herramientas y comandos de la persona.
// El directorio contenedor se elimina solo si queda vacío, que es la señal de
// que era enteramente nuestro.
func removeNativeWrappers(target string) {
	retirados := 0
	for _, seg := range setup.GeneratedWrapperPaths() {
		ruta := filepath.Join(append([]string{target}, seg...)...)
		if _, err := os.Stat(ruta); err != nil {
			continue
		}
		if err := os.Remove(ruta); err != nil {
			fmt.Printf("  ⚠️  %s: error al eliminar: %v\n", filepath.Join(seg...), err)
			continue
		}
		retirados++
		// Si el envoltorio vivía en su propio subdirectorio y ese subdirectorio
		// queda vacío, era nuestro por completo.
		if dir := filepath.Dir(ruta); dir != target {
			if entradas, err := os.ReadDir(dir); err == nil && len(entradas) == 0 {
				os.Remove(dir)
			}
		}
	}
	if retirados > 0 {
		fmt.Printf("  ✅ %d envoltorio(s) nativo(s) retirado(s)\n", retirados)
	} else {
		fmt.Println("  ℹ️  envoltorios nativos: no encontrados")
	}
}

func removeMemoryDir(target, memDir string) {
	path := filepath.Join(target, memDir)
	if _, err := os.Stat(path); err != nil {
		fmt.Printf("  ℹ️  %s: no encontrado\n", memDir)
		return
	}
	if err := os.RemoveAll(path); err != nil {
		fmt.Printf("  ⚠️  %s: error al eliminar: %v\n", memDir, err)
		return
	}
	fmt.Printf("  ✅ %s: eliminado (datos incluidos)\n", memDir)
}

func removeBinary(target string) {
	destBin := filepath.Join(target, "mem")
	if _, err := os.Stat(destBin); err != nil {
		fmt.Println("  ℹ️  binario mem: no encontrado")
		return
	}
	if err := os.Remove(destBin); err != nil {
		fmt.Printf("  ⚠️  binario mem: no se pudo eliminar (%v). Si es el binario en ejecución (común en Windows), bórralo manualmente al cerrar este proceso.\n", err)
		return
	}
	fmt.Printf("  ✅ binario %s eliminado\n", destBin)
}
